apiVersion: v1
kind: Secret
metadata:
  name: mc-demo-postgres
  namespace: mission-control
  labels:
    app.kubernetes.io/part-of: mc-demo-app
  annotations:
    demo.flanksource.com/source-secret: mc-demo/mc-demo-postgres
type: Opaque
stringData:
  username: demo
  password: demo
