apiVersion: v1
kind: Secret
metadata:
  name: mc-demo-postgres
  namespace: mc-demo
  labels:
    app.kubernetes.io/part-of: mc-demo-app
type: Opaque
stringData:
  username: demo
  password: demo
  database: demo
  url: postgres://demo:demo@postgres.mc-demo.svc.cluster.local:5432/demo?sslmode=disable
